apiVersion: apps/v1
kind: Deployment
metadata:
  name: duoc-app-blue
  labels:
    app: duoc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duoc-app
      version: blue
  template:
    metadata:
      labels:
        app: duoc-app
        version: blue
    spec:
      containers:
      - name: node-app-container
        image: 575508784185.dkr.ecr.us-east-1.amazonaws.com/duoc-lab:v1
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: duoc-app-bg-service
spec:
  selector:
    version: blue
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duoc-app-green
  labels:
    app: duoc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duoc-app
      version: green
  template:
    metadata:
      labels:
        app: duoc-app
        version: green
    spec:
      containers:
      - name: node-app-container
        image: 575508784185.dkr.ecr.us-east-1.amazonaws.com/duoc-lab:v2
        ports:
        - containerPort: 3000
        imagePullPolicy: Always