name: CD Pipeline Blue-Green con Rollback

on:
  workflow_dispatch:

jobs:
  deploy-blue-green:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Configurar kubectl
        run: |
          aws eks update-kubeconfig --name duoc-eks-cluster-cli --region us-east-1
          kubectl get nodes

      - name: Deploy Blue-Green
        id: deploy-step
        run: |
          kubectl apply -f k8s/blue-green.yaml
          kubectl rollout status deployment/duoc-app-green --timeout=90s

      - name: Validación de salud Green
        id: health-check
        run: |
          kubectl wait --for=condition=ready pod -l app=duoc-app,version=green --timeout=90s
          kubectl get pods -l app=duoc-app,version=green

      - name: Cambiar tráfico a Green
        run: |
          kubectl patch service duoc-app-bg-service -p '{"spec":{"selector":{"app":"duoc-app","version":"green"}}}'
          echo "Tráfico cambiado correctamente a Green."

      - name: Rollback automático a Blue
        if: failure()
        run: |
          echo "Fallo detectado. Ejecutando rollback automático..."
          kubectl patch service duoc-app-bg-service -p '{"spec":{"selector":{"app":"duoc-app","version":"blue"}}}'
          echo "Rollback completado. El tráfico volvió a Blue."