name: Pipeline de Test (validación)

on:
  push:
    branches:
      - main

jobs:

  validate-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Linting Check
        run: |
          npm install eslint
          npm run lint

  security-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: NPM Audit
        run: npm audit --audit-level=critical

  test:
    needs:
      - validate-code
      - security-audit

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: |
          echo "Fallo controlado para evidencia EA3"
          exit 1

      - name: Validar construcción Docker
        run: docker build -t validacion-local:${{ github.sha }} .